 table_schema |          table_name          | privilege_type |    grantee     
--------------+------------------------------+----------------+----------------
 public       | admin_pins                   | SELECT         | audit_readonly
 public       | admin_pins                   | DELETE         | copilot_edit
 public       | admin_pins                   | INSERT         | copilot_edit
 public       | admin_pins                   | SELECT         | copilot_edit
 public       | admin_pins                   | UPDATE         | copilot_edit
 public       | admin_pins                   | DELETE         | postgres
 public       | admin_pins                   | INSERT         | postgres
 public       | admin_pins                   | REFERENCES     | postgres
 public       | admin_pins                   | SELECT         | postgres
 public       | admin_pins                   | TRIGGER        | postgres
 public       | admin_pins                   | TRUNCATE       | postgres
 public       | admin_pins                   | UPDATE         | postgres
 public       | admin_pins                   | DELETE         | service_role
 public       | admin_pins                   | INSERT         | service_role
 public       | admin_pins                   | REFERENCES     | service_role
 public       | admin_pins                   | SELECT         | service_role
 public       | admin_pins                   | TRIGGER        | service_role
 public       | admin_pins                   | TRUNCATE       | service_role
 public       | admin_pins                   | UPDATE         | service_role
 public       | app_settings                 | SELECT         | audit_readonly
 public       | app_settings                 | DELETE         | copilot_edit
 public       | app_settings                 | INSERT         | copilot_edit
 public       | app_settings                 | SELECT         | copilot_edit
 public       | app_settings                 | UPDATE         | copilot_edit
 public       | app_settings                 | DELETE         | postgres
 public       | app_settings                 | INSERT         | postgres
 public       | app_settings                 | REFERENCES     | postgres
 public       | app_settings                 | SELECT         | postgres
 public       | app_settings                 | TRIGGER        | postgres
 public       | app_settings                 | TRUNCATE       | postgres
 public       | app_settings                 | UPDATE         | postgres
 public       | app_settings                 | DELETE         | service_role
 public       | app_settings                 | INSERT         | service_role
 public       | app_settings                 | REFERENCES     | service_role
 public       | app_settings                 | SELECT         | service_role
 public       | app_settings                 | TRIGGER        | service_role
 public       | app_settings                 | TRUNCATE       | service_role
 public       | app_settings                 | UPDATE         | service_role
 public       | audit_logs                   | SELECT         | audit_readonly
 public       | audit_logs                   | DELETE         | copilot_edit
 public       | audit_logs                   | INSERT         | copilot_edit
 public       | audit_logs                   | SELECT         | copilot_edit
 public       | audit_logs                   | UPDATE         | copilot_edit
 public       | audit_logs                   | DELETE         | postgres
 public       | audit_logs                   | INSERT         | postgres
 public       | audit_logs                   | REFERENCES     | postgres
 public       | audit_logs                   | SELECT         | postgres
 public       | audit_logs                   | TRIGGER        | postgres
 public       | audit_logs                   | TRUNCATE       | postgres
 public       | audit_logs                   | UPDATE         | postgres
 public       | audit_logs                   | DELETE         | service_role
 public       | audit_logs                   | INSERT         | service_role
 public       | audit_logs                   | REFERENCES     | service_role
 public       | audit_logs                   | SELECT         | service_role
 public       | audit_logs                   | TRIGGER        | service_role
 public       | audit_logs                   | TRUNCATE       | service_role
 public       | audit_logs                   | UPDATE         | service_role
 public       | bank_holidays                | SELECT         | audit_readonly
 public       | bank_holidays                | DELETE         | copilot_edit
 public       | bank_holidays                | INSERT         | copilot_edit
 public       | bank_holidays                | SELECT         | copilot_edit
 public       | bank_holidays                | UPDATE         | copilot_edit
 public       | bank_holidays                | DELETE         | postgres
 public       | bank_holidays                | INSERT         | postgres
 public       | bank_holidays                | REFERENCES     | postgres
 public       | bank_holidays                | SELECT         | postgres
 public       | bank_holidays                | TRIGGER        | postgres
 public       | bank_holidays                | TRUNCATE       | postgres
 public       | bank_holidays                | UPDATE         | postgres
 public       | bank_holidays                | DELETE         | service_role
 public       | bank_holidays                | INSERT         | service_role
 public       | bank_holidays                | REFERENCES     | service_role
 public       | bank_holidays                | SELECT         | service_role
 public       | bank_holidays                | TRIGGER        | service_role
 public       | bank_holidays                | TRUNCATE       | service_role
 public       | bank_holidays                | UPDATE         | service_role
 public       | calendar_tokens              | SELECT         | audit_readonly
 public       | calendar_tokens              | DELETE         | copilot_edit
 public       | calendar_tokens              | INSERT         | copilot_edit
 public       | calendar_tokens              | SELECT         | copilot_edit
 public       | calendar_tokens              | UPDATE         | copilot_edit
 public       | calendar_tokens              | DELETE         | postgres
 public       | calendar_tokens              | INSERT         | postgres
 public       | calendar_tokens              | REFERENCES     | postgres
 public       | calendar_tokens              | SELECT         | postgres
 public       | calendar_tokens              | TRIGGER        | postgres
 public       | calendar_tokens              | TRUNCATE       | postgres
 public       | calendar_tokens              | UPDATE         | postgres
 public       | calendar_tokens              | DELETE         | service_role
 public       | calendar_tokens              | INSERT         | service_role
 public       | calendar_tokens              | REFERENCES     | service_role
 public       | calendar_tokens              | SELECT         | service_role
 public       | calendar_tokens              | TRIGGER        | service_role
 public       | calendar_tokens              | TRUNCATE       | service_role
 public       | calendar_tokens              | UPDATE         | service_role
 public       | login_audit                  | SELECT         | audit_readonly
 public       | login_audit                  | DELETE         | copilot_edit
 public       | login_audit                  | INSERT         | copilot_edit
 public       | login_audit                  | SELECT         | copilot_edit
 public       | login_audit                  | UPDATE         | copilot_edit
 public       | login_audit                  | DELETE         | postgres
 public       | login_audit                  | INSERT         | postgres
 public       | login_audit                  | REFERENCES     | postgres
 public       | login_audit                  | SELECT         | postgres
 public       | login_audit                  | TRIGGER        | postgres
 public       | login_audit                  | TRUNCATE       | postgres
 public       | login_audit                  | UPDATE         | postgres
 public       | login_audit                  | DELETE         | service_role
 public       | login_audit                  | INSERT         | service_role
 public       | login_audit                  | REFERENCES     | service_role
 public       | login_audit                  | SELECT         | service_role
 public       | login_audit                  | TRIGGER        | service_role
 public       | login_audit                  | TRUNCATE       | service_role
 public       | login_audit                  | UPDATE         | service_role
 public       | login_rate_limiting          | SELECT         | audit_readonly
 public       | login_rate_limiting          | DELETE         | copilot_edit
 public       | login_rate_limiting          | INSERT         | copilot_edit
 public       | login_rate_limiting          | SELECT         | copilot_edit
 public       | login_rate_limiting          | UPDATE         | copilot_edit
 public       | login_rate_limiting          | DELETE         | postgres
 public       | login_rate_limiting          | INSERT         | postgres
 public       | login_rate_limiting          | REFERENCES     | postgres
 public       | login_rate_limiting          | SELECT         | postgres
 public       | login_rate_limiting          | TRIGGER        | postgres
 public       | login_rate_limiting          | TRUNCATE       | postgres
 public       | login_rate_limiting          | UPDATE         | postgres
 public       | login_rate_limiting          | DELETE         | service_role
 public       | login_rate_limiting          | INSERT         | service_role
 public       | login_rate_limiting          | REFERENCES     | service_role
 public       | login_rate_limiting          | SELECT         | service_role
 public       | login_rate_limiting          | TRIGGER        | service_role
 public       | login_rate_limiting          | TRUNCATE       | service_role
 public       | login_rate_limiting          | UPDATE         | service_role
 public       | non_staff_people             | SELECT         | audit_readonly
 public       | non_staff_people             | DELETE         | copilot_edit
 public       | non_staff_people             | INSERT         | copilot_edit
 public       | non_staff_people             | SELECT         | copilot_edit
 public       | non_staff_people             | UPDATE         | copilot_edit
 public       | non_staff_people             | DELETE         | postgres
 public       | non_staff_people             | INSERT         | postgres
 public       | non_staff_people             | REFERENCES     | postgres
 public       | non_staff_people             | SELECT         | postgres
 public       | non_staff_people             | TRIGGER        | postgres
 public       | non_staff_people             | TRUNCATE       | postgres
 public       | non_staff_people             | UPDATE         | postgres
 public       | non_staff_people             | DELETE         | service_role
 public       | non_staff_people             | INSERT         | service_role
 public       | non_staff_people             | REFERENCES     | service_role
 public       | non_staff_people             | SELECT         | service_role
 public       | non_staff_people             | TRIGGER        | service_role
 public       | non_staff_people             | TRUNCATE       | service_role
 public       | non_staff_people             | UPDATE         | service_role
 public       | notice_ack                   | SELECT         | audit_readonly
 public       | notice_ack                   | DELETE         | copilot_edit
 public       | notice_ack                   | INSERT         | copilot_edit
 public       | notice_ack                   | SELECT         | copilot_edit
 public       | notice_ack                   | UPDATE         | copilot_edit
 public       | notice_ack                   | DELETE         | postgres
 public       | notice_ack                   | INSERT         | postgres
 public       | notice_ack                   | REFERENCES     | postgres
 public       | notice_ack                   | SELECT         | postgres
 public       | notice_ack                   | TRIGGER        | postgres
 public       | notice_ack                   | TRUNCATE       | postgres
 public       | notice_ack                   | UPDATE         | postgres
 public       | notice_ack                   | DELETE         | service_role
 public       | notice_ack                   | INSERT         | service_role
 public       | notice_ack                   | REFERENCES     | service_role
 public       | notice_ack                   | SELECT         | service_role
 public       | notice_ack                   | TRIGGER        | service_role
 public       | notice_ack                   | TRUNCATE       | service_role
 public       | notice_ack                   | UPDATE         | service_role
 public       | notice_targets               | SELECT         | audit_readonly
 public       | notice_targets               | DELETE         | copilot_edit
 public       | notice_targets               | INSERT         | copilot_edit
 public       | notice_targets               | SELECT         | copilot_edit
 public       | notice_targets               | UPDATE         | copilot_edit
 public       | notice_targets               | DELETE         | postgres
 public       | notice_targets               | INSERT         | postgres
 public       | notice_targets               | REFERENCES     | postgres
 public       | notice_targets               | SELECT         | postgres
 public       | notice_targets               | TRIGGER        | postgres
 public       | notice_targets               | TRUNCATE       | postgres
 public       | notice_targets               | UPDATE         | postgres
 public       | notice_targets               | DELETE         | service_role
 public       | notice_targets               | INSERT         | service_role
 public       | notice_targets               | REFERENCES     | service_role
 public       | notice_targets               | SELECT         | service_role
 public       | notice_targets               | TRIGGER        | service_role
 public       | notice_targets               | TRUNCATE       | service_role
 public       | notice_targets               | UPDATE         | service_role
 public       | notices                      | SELECT         | audit_readonly
 public       | notices                      | DELETE         | copilot_edit
 public       | notices                      | INSERT         | copilot_edit
 public       | notices                      | SELECT         | copilot_edit
 public       | notices                      | UPDATE         | copilot_edit
 public       | notices                      | DELETE         | postgres
 public       | notices                      | INSERT         | postgres
 public       | notices                      | REFERENCES     | postgres
 public       | notices                      | SELECT         | postgres
 public       | notices                      | TRIGGER        | postgres
 public       | notices                      | TRUNCATE       | postgres
 public       | notices                      | UPDATE         | postgres
 public       | notices                      | DELETE         | service_role
 public       | notices                      | INSERT         | service_role
 public       | notices                      | REFERENCES     | service_role
 public       | notices                      | SELECT         | service_role
 public       | notices                      | TRIGGER        | service_role
 public       | notices                      | TRUNCATE       | service_role
 public       | notices                      | UPDATE         | service_role
 public       | notifications                | SELECT         | audit_readonly
 public       | notifications                | DELETE         | copilot_edit
 public       | notifications                | INSERT         | copilot_edit
 public       | notifications                | SELECT         | copilot_edit
 public       | notifications                | UPDATE         | copilot_edit
 public       | notifications                | DELETE         | postgres
 public       | notifications                | INSERT         | postgres
 public       | notifications                | REFERENCES     | postgres
 public       | notifications                | SELECT         | postgres
 public       | notifications                | TRIGGER        | postgres
 public       | notifications                | TRUNCATE       | postgres
 public       | notifications                | UPDATE         | postgres
 public       | notifications                | DELETE         | service_role
 public       | notifications                | INSERT         | service_role
 public       | notifications                | REFERENCES     | service_role
 public       | notifications                | SELECT         | service_role
 public       | notifications                | TRIGGER        | service_role
 public       | notifications                | TRUNCATE       | service_role
 public       | notifications                | UPDATE         | service_role
 public       | operation_rate_limits        | SELECT         | audit_readonly
 public       | operation_rate_limits        | DELETE         | copilot_edit
 public       | operation_rate_limits        | INSERT         | copilot_edit
 public       | operation_rate_limits        | SELECT         | copilot_edit
 public       | operation_rate_limits        | UPDATE         | copilot_edit
 public       | operation_rate_limits        | DELETE         | postgres
 public       | operation_rate_limits        | INSERT         | postgres
 public       | operation_rate_limits        | REFERENCES     | postgres
 public       | operation_rate_limits        | SELECT         | postgres
 public       | operation_rate_limits        | TRIGGER        | postgres
 public       | operation_rate_limits        | TRUNCATE       | postgres
 public       | operation_rate_limits        | UPDATE         | postgres
 public       | operation_rate_limits        | DELETE         | service_role
 public       | operation_rate_limits        | INSERT         | service_role
 public       | operation_rate_limits        | REFERENCES     | service_role
 public       | operation_rate_limits        | SELECT         | service_role
 public       | operation_rate_limits        | TRIGGER        | service_role
 public       | operation_rate_limits        | TRUNCATE       | service_role
 public       | operation_rate_limits        | UPDATE         | service_role
 public       | pattern_definitions          | SELECT         | audit_readonly
 public       | pattern_definitions          | DELETE         | copilot_edit
 public       | pattern_definitions          | INSERT         | copilot_edit
 public       | pattern_definitions          | SELECT         | copilot_edit
 public       | pattern_definitions          | UPDATE         | copilot_edit
 public       | pattern_definitions          | DELETE         | postgres
 public       | pattern_definitions          | INSERT         | postgres
 public       | pattern_definitions          | REFERENCES     | postgres
 public       | pattern_definitions          | SELECT         | postgres
 public       | pattern_definitions          | TRIGGER        | postgres
 public       | pattern_definitions          | TRUNCATE       | postgres
 public       | pattern_definitions          | UPDATE         | postgres
 public       | pattern_definitions          | DELETE         | service_role
 public       | pattern_definitions          | INSERT         | service_role
 public       | pattern_definitions          | REFERENCES     | service_role
 public       | pattern_definitions          | SELECT         | service_role
 public       | pattern_definitions          | TRIGGER        | service_role
 public       | pattern_definitions          | TRUNCATE       | service_role
 public       | pattern_definitions          | UPDATE         | service_role
 public       | pattern_templates            | SELECT         | audit_readonly
 public       | pattern_templates            | DELETE         | copilot_edit
 public       | pattern_templates            | INSERT         | copilot_edit
 public       | pattern_templates            | SELECT         | copilot_edit
 public       | pattern_templates            | UPDATE         | copilot_edit
 public       | pattern_templates            | DELETE         | postgres
 public       | pattern_templates            | INSERT         | postgres
 public       | pattern_templates            | REFERENCES     | postgres
 public       | pattern_templates            | SELECT         | postgres
 public       | pattern_templates            | TRIGGER        | postgres
 public       | pattern_templates            | TRUNCATE       | postgres
 public       | pattern_templates            | UPDATE         | postgres
 public       | pattern_templates            | DELETE         | service_role
 public       | pattern_templates            | INSERT         | service_role
 public       | pattern_templates            | REFERENCES     | service_role
 public       | pattern_templates            | SELECT         | service_role
 public       | pattern_templates            | TRIGGER        | service_role
 public       | pattern_templates            | TRUNCATE       | service_role
 public       | pattern_templates            | UPDATE         | service_role
 public       | period_non_staff             | SELECT         | audit_readonly
 public       | period_non_staff             | DELETE         | copilot_edit
 public       | period_non_staff             | INSERT         | copilot_edit
 public       | period_non_staff             | SELECT         | copilot_edit
 public       | period_non_staff             | UPDATE         | copilot_edit
 public       | period_non_staff             | DELETE         | postgres
 public       | period_non_staff             | INSERT         | postgres
 public       | period_non_staff             | REFERENCES     | postgres
 public       | period_non_staff             | SELECT         | postgres
 public       | period_non_staff             | TRIGGER        | postgres
 public       | period_non_staff             | TRUNCATE       | postgres
 public       | period_non_staff             | UPDATE         | postgres
 public       | period_non_staff             | DELETE         | service_role
 public       | period_non_staff             | INSERT         | service_role
 public       | period_non_staff             | REFERENCES     | service_role
 public       | period_non_staff             | SELECT         | service_role
 public       | period_non_staff             | TRIGGER        | service_role
 public       | period_non_staff             | TRUNCATE       | service_role
 public       | period_non_staff             | UPDATE         | service_role
 public       | permission_group_permissions | SELECT         | audit_readonly
 public       | permission_group_permissions | DELETE         | copilot_edit
 public       | permission_group_permissions | INSERT         | copilot_edit
 public       | permission_group_permissions | SELECT         | copilot_edit
 public       | permission_group_permissions | UPDATE         | copilot_edit
 public       | permission_group_permissions | DELETE         | postgres
 public       | permission_group_permissions | INSERT         | postgres
 public       | permission_group_permissions | REFERENCES     | postgres
 public       | permission_group_permissions | SELECT         | postgres
 public       | permission_group_permissions | TRIGGER        | postgres
 public       | permission_group_permissions | TRUNCATE       | postgres
 public       | permission_group_permissions | UPDATE         | postgres
 public       | permission_group_permissions | DELETE         | service_role
 public       | permission_group_permissions | INSERT         | service_role
 public       | permission_group_permissions | REFERENCES     | service_role
 public       | permission_group_permissions | SELECT         | service_role
 public       | permission_group_permissions | TRIGGER        | service_role
 public       | permission_group_permissions | TRUNCATE       | service_role
 public       | permission_group_permissions | UPDATE         | service_role
 public       | permission_groups            | SELECT         | audit_readonly
 public       | permission_groups            | DELETE         | copilot_edit
 public       | permission_groups            | INSERT         | copilot_edit
 public       | permission_groups            | SELECT         | copilot_edit
 public       | permission_groups            | UPDATE         | copilot_edit
 public       | permission_groups            | DELETE         | postgres
 public       | permission_groups            | INSERT         | postgres
 public       | permission_groups            | REFERENCES     | postgres
 public       | permission_groups            | SELECT         | postgres
 public       | permission_groups            | TRIGGER        | postgres
 public       | permission_groups            | TRUNCATE       | postgres
 public       | permission_groups            | UPDATE         | postgres
 public       | permission_groups            | DELETE         | service_role
 public       | permission_groups            | INSERT         | service_role
 public       | permission_groups            | REFERENCES     | service_role
 public       | permission_groups            | SELECT         | service_role
 public       | permission_groups            | TRIGGER        | service_role
 public       | permission_groups            | TRUNCATE       | service_role
 public       | permission_groups            | UPDATE         | service_role
 public       | permissions                  | SELECT         | audit_readonly
 public       | permissions                  | DELETE         | copilot_edit
 public       | permissions                  | INSERT         | copilot_edit
 public       | permissions                  | SELECT         | copilot_edit
 public       | permissions                  | UPDATE         | copilot_edit
 public       | permissions                  | DELETE         | postgres
 public       | permissions                  | INSERT         | postgres
 public       | permissions                  | REFERENCES     | postgres
 public       | permissions                  | SELECT         | postgres
 public       | permissions                  | TRIGGER        | postgres
 public       | permissions                  | TRUNCATE       | postgres
 public       | permissions                  | UPDATE         | postgres
 public       | permissions                  | DELETE         | service_role
 public       | permissions                  | INSERT         | service_role
 public       | permissions                  | REFERENCES     | service_role
 public       | permissions                  | SELECT         | service_role
 public       | permissions                  | TRIGGER        | service_role
 public       | permissions                  | TRUNCATE       | service_role
 public       | permissions                  | UPDATE         | service_role
 public       | planned_assignments          | SELECT         | audit_readonly
 public       | planned_assignments          | DELETE         | copilot_edit
 public       | planned_assignments          | INSERT         | copilot_edit
 public       | planned_assignments          | SELECT         | copilot_edit
 public       | planned_assignments          | UPDATE         | copilot_edit
 public       | planned_assignments          | DELETE         | postgres
 public       | planned_assignments          | INSERT         | postgres
 public       | planned_assignments          | REFERENCES     | postgres
 public       | planned_assignments          | SELECT         | postgres
 public       | planned_assignments          | TRIGGER        | postgres
 public       | planned_assignments          | TRUNCATE       | postgres
 public       | planned_assignments          | UPDATE         | postgres
 public       | planned_assignments          | DELETE         | service_role
 public       | planned_assignments          | INSERT         | service_role
 public       | planned_assignments          | REFERENCES     | service_role
 public       | planned_assignments          | SELECT         | service_role
 public       | planned_assignments          | TRIGGER        | service_role
 public       | planned_assignments          | TRUNCATE       | service_role
 public       | planned_assignments          | UPDATE         | service_role
 public       | request_cell_locks           | SELECT         | audit_readonly
 public       | request_cell_locks           | DELETE         | copilot_edit
 public       | request_cell_locks           | INSERT         | copilot_edit
 public       | request_cell_locks           | SELECT         | copilot_edit
 public       | request_cell_locks           | UPDATE         | copilot_edit
 public       | request_cell_locks           | DELETE         | postgres
 public       | request_cell_locks           | INSERT         | postgres
 public       | request_cell_locks           | REFERENCES     | postgres
 public       | request_cell_locks           | SELECT         | postgres
 public       | request_cell_locks           | TRIGGER        | postgres
 public       | request_cell_locks           | TRUNCATE       | postgres
 public       | request_cell_locks           | UPDATE         | postgres
 public       | request_cell_locks           | DELETE         | service_role
 public       | request_cell_locks           | INSERT         | service_role
 public       | request_cell_locks           | REFERENCES     | service_role
 public       | request_cell_locks           | SELECT         | service_role
 public       | request_cell_locks           | TRIGGER        | service_role
 public       | request_cell_locks           | TRUNCATE       | service_role
 public       | request_cell_locks           | UPDATE         | service_role
 public       | requests                     | SELECT         | audit_readonly
 public       | requests                     | DELETE         | copilot_edit
 public       | requests                     | INSERT         | copilot_edit
 public       | requests                     | SELECT         | copilot_edit
 public       | requests                     | UPDATE         | copilot_edit
 public       | requests                     | DELETE         | postgres
 public       | requests                     | INSERT         | postgres
 public       | requests                     | REFERENCES     | postgres
 public       | requests                     | SELECT         | postgres
 public       | requests                     | TRIGGER        | postgres
 public       | requests                     | TRUNCATE       | postgres
 public       | requests                     | UPDATE         | postgres
 public       | requests                     | DELETE         | service_role
 public       | requests                     | INSERT         | service_role
 public       | requests                     | REFERENCES     | service_role
 public       | requests                     | SELECT         | service_role
 public       | requests                     | TRIGGER        | service_role
 public       | requests                     | TRUNCATE       | service_role
 public       | requests                     | UPDATE         | service_role
 public       | roles                        | SELECT         | audit_readonly
 public       | roles                        | DELETE         | copilot_edit
 public       | roles                        | INSERT         | copilot_edit
 public       | roles                        | SELECT         | copilot_edit
 public       | roles                        | UPDATE         | copilot_edit
 public       | roles                        | DELETE         | postgres
 public       | roles                        | INSERT         | postgres
 public       | roles                        | REFERENCES     | postgres
 public       | roles                        | SELECT         | postgres
 public       | roles                        | TRIGGER        | postgres
 public       | roles                        | TRUNCATE       | postgres
 public       | roles                        | UPDATE         | postgres
 public       | roles                        | DELETE         | service_role
 public       | roles                        | INSERT         | service_role
 public       | roles                        | REFERENCES     | service_role
 public       | roles                        | SELECT         | service_role
 public       | roles                        | TRIGGER        | service_role
 public       | roles                        | TRUNCATE       | service_role
 public       | roles                        | UPDATE         | service_role
 public       | rota_assignment_audits       | SELECT         | audit_readonly
 public       | rota_assignment_audits       | DELETE         | copilot_edit
 public       | rota_assignment_audits       | INSERT         | copilot_edit
 public       | rota_assignment_audits       | SELECT         | copilot_edit
 public       | rota_assignment_audits       | UPDATE         | copilot_edit
 public       | rota_assignment_audits       | DELETE         | postgres
 public       | rota_assignment_audits       | INSERT         | postgres
 public       | rota_assignment_audits       | REFERENCES     | postgres
 public       | rota_assignment_audits       | SELECT         | postgres
 public       | rota_assignment_audits       | TRIGGER        | postgres
 public       | rota_assignment_audits       | TRUNCATE       | postgres
 public       | rota_assignment_audits       | UPDATE         | postgres
 public       | rota_assignment_audits       | DELETE         | service_role
 public       | rota_assignment_audits       | INSERT         | service_role
 public       | rota_assignment_audits       | REFERENCES     | service_role
 public       | rota_assignment_audits       | SELECT         | service_role
 public       | rota_assignment_audits       | TRIGGER        | service_role
 public       | rota_assignment_audits       | TRUNCATE       | service_role
 public       | rota_assignment_audits       | UPDATE         | service_role
 public       | rota_assignment_comments     | SELECT         | audit_readonly
 public       | rota_assignment_comments     | DELETE         | copilot_edit
 public       | rota_assignment_comments     | INSERT         | copilot_edit
 public       | rota_assignment_comments     | SELECT         | copilot_edit
 public       | rota_assignment_comments     | UPDATE         | copilot_edit
 public       | rota_assignment_comments     | DELETE         | postgres
 public       | rota_assignment_comments     | INSERT         | postgres
 public       | rota_assignment_comments     | REFERENCES     | postgres
 public       | rota_assignment_comments     | SELECT         | postgres
 public       | rota_assignment_comments     | TRIGGER        | postgres
 public       | rota_assignment_comments     | TRUNCATE       | postgres
 public       | rota_assignment_comments     | UPDATE         | postgres
 public       | rota_assignment_comments     | DELETE         | service_role
 public       | rota_assignment_comments     | INSERT         | service_role
 public       | rota_assignment_comments     | REFERENCES     | service_role
 public       | rota_assignment_comments     | SELECT         | service_role
 public       | rota_assignment_comments     | TRIGGER        | service_role
 public       | rota_assignment_comments     | TRUNCATE       | service_role
 public       | rota_assignment_comments     | UPDATE         | service_role
 public       | rota_assignment_history      | SELECT         | audit_readonly
 public       | rota_assignment_history      | DELETE         | copilot_edit
 public       | rota_assignment_history      | INSERT         | copilot_edit
 public       | rota_assignment_history      | SELECT         | copilot_edit
 public       | rota_assignment_history      | UPDATE         | copilot_edit
 public       | rota_assignment_history      | DELETE         | postgres
 public       | rota_assignment_history      | INSERT         | postgres
 public       | rota_assignment_history      | REFERENCES     | postgres
 public       | rota_assignment_history      | SELECT         | postgres
 public       | rota_assignment_history      | TRIGGER        | postgres
 public       | rota_assignment_history      | TRUNCATE       | postgres
 public       | rota_assignment_history      | UPDATE         | postgres
 public       | rota_assignment_history      | DELETE         | service_role
 public       | rota_assignment_history      | INSERT         | service_role
 public       | rota_assignment_history      | REFERENCES     | service_role
 public       | rota_assignment_history      | SELECT         | service_role
 public       | rota_assignment_history      | TRIGGER        | service_role
 public       | rota_assignment_history      | TRUNCATE       | service_role
 public       | rota_assignment_history      | UPDATE         | service_role
 public       | rota_assignment_overrides    | SELECT         | audit_readonly
 public       | rota_assignment_overrides    | DELETE         | copilot_edit
 public       | rota_assignment_overrides    | INSERT         | copilot_edit
 public       | rota_assignment_overrides    | SELECT         | copilot_edit
 public       | rota_assignment_overrides    | UPDATE         | copilot_edit
 public       | rota_assignment_overrides    | DELETE         | postgres
 public       | rota_assignment_overrides    | INSERT         | postgres
 public       | rota_assignment_overrides    | REFERENCES     | postgres
 public       | rota_assignment_overrides    | SELECT         | postgres
 public       | rota_assignment_overrides    | TRIGGER        | postgres
 public       | rota_assignment_overrides    | TRUNCATE       | postgres
 public       | rota_assignment_overrides    | UPDATE         | postgres
 public       | rota_assignment_overrides    | DELETE         | service_role
 public       | rota_assignment_overrides    | INSERT         | service_role
 public       | rota_assignment_overrides    | REFERENCES     | service_role
 public       | rota_assignment_overrides    | SELECT         | service_role
 public       | rota_assignment_overrides    | TRIGGER        | service_role
 public       | rota_assignment_overrides    | TRUNCATE       | service_role
 public       | rota_assignment_overrides    | UPDATE         | service_role
 public       | rota_assignments             | SELECT         | audit_readonly
 public       | rota_assignments             | DELETE         | copilot_edit
 public       | rota_assignments             | INSERT         | copilot_edit
 public       | rota_assignments             | SELECT         | copilot_edit
 public       | rota_assignments             | UPDATE         | copilot_edit
 public       | rota_assignments             | DELETE         | postgres
 public       | rota_assignments             | INSERT         | postgres
 public       | rota_assignments             | REFERENCES     | postgres
 public       | rota_assignments             | SELECT         | postgres
 public       | rota_assignments             | TRIGGER        | postgres
 public       | rota_assignments             | TRUNCATE       | postgres
 public       | rota_assignments             | UPDATE         | postgres
 public       | rota_assignments             | DELETE         | service_role
 public       | rota_assignments             | INSERT         | service_role
 public       | rota_assignments             | REFERENCES     | service_role
 public       | rota_assignments             | SELECT         | service_role
 public       | rota_assignments             | TRIGGER        | service_role
 public       | rota_assignments             | TRUNCATE       | service_role
 public       | rota_assignments             | UPDATE         | service_role
 public       | rota_dates                   | SELECT         | audit_readonly
 public       | rota_dates                   | DELETE         | copilot_edit
 public       | rota_dates                   | INSERT         | copilot_edit
 public       | rota_dates                   | SELECT         | copilot_edit
 public       | rota_dates                   | UPDATE         | copilot_edit
 public       | rota_dates                   | DELETE         | postgres
 public       | rota_dates                   | INSERT         | postgres
 public       | rota_dates                   | REFERENCES     | postgres
 public       | rota_dates                   | SELECT         | postgres
 public       | rota_dates                   | TRIGGER        | postgres
 public       | rota_dates                   | TRUNCATE       | postgres
 public       | rota_dates                   | UPDATE         | postgres
 public       | rota_dates                   | DELETE         | service_role
 public       | rota_dates                   | INSERT         | service_role
 public       | rota_dates                   | REFERENCES     | service_role
 public       | rota_dates                   | SELECT         | service_role
 public       | rota_dates                   | TRIGGER        | service_role
 public       | rota_dates                   | TRUNCATE       | service_role
 public       | rota_dates                   | UPDATE         | service_role
 public       | rota_periods                 | SELECT         | audit_readonly
 public       | rota_periods                 | DELETE         | copilot_edit
 public       | rota_periods                 | INSERT         | copilot_edit
 public       | rota_periods                 | SELECT         | copilot_edit
 public       | rota_periods                 | UPDATE         | copilot_edit
 public       | rota_periods                 | DELETE         | postgres
 public       | rota_periods                 | INSERT         | postgres
 public       | rota_periods                 | REFERENCES     | postgres
 public       | rota_periods                 | SELECT         | postgres
 public       | rota_periods                 | TRIGGER        | postgres
 public       | rota_periods                 | TRUNCATE       | postgres
 public       | rota_periods                 | UPDATE         | postgres
 public       | rota_periods                 | DELETE         | service_role
 public       | rota_periods                 | INSERT         | service_role
 public       | rota_periods                 | REFERENCES     | service_role
 public       | rota_periods                 | SELECT         | service_role
 public       | rota_periods                 | TRIGGER        | service_role
 public       | rota_periods                 | TRUNCATE       | service_role
 public       | rota_periods                 | UPDATE         | service_role
 public       | rota_weeks                   | SELECT         | audit_readonly
 public       | rota_weeks                   | DELETE         | copilot_edit
 public       | rota_weeks                   | INSERT         | copilot_edit
 public       | rota_weeks                   | SELECT         | copilot_edit
 public       | rota_weeks                   | UPDATE         | copilot_edit
 public       | rota_weeks                   | DELETE         | postgres
 public       | rota_weeks                   | INSERT         | postgres
 public       | rota_weeks                   | REFERENCES     | postgres
 public       | rota_weeks                   | SELECT         | postgres
 public       | rota_weeks                   | TRIGGER        | postgres
 public       | rota_weeks                   | TRUNCATE       | postgres
 public       | rota_weeks                   | UPDATE         | postgres
 public       | rota_weeks                   | DELETE         | service_role
 public       | rota_weeks                   | INSERT         | service_role
 public       | rota_weeks                   | REFERENCES     | service_role
 public       | rota_weeks                   | SELECT         | service_role
 public       | rota_weeks                   | TRIGGER        | service_role
 public       | rota_weeks                   | TRUNCATE       | service_role
 public       | rota_weeks                   | UPDATE         | service_role
 public       | sessions                     | SELECT         | audit_readonly
 public       | sessions                     | DELETE         | copilot_edit
 public       | sessions                     | INSERT         | copilot_edit
 public       | sessions                     | SELECT         | copilot_edit
 public       | sessions                     | UPDATE         | copilot_edit
 public       | sessions                     | DELETE         | postgres
 public       | sessions                     | INSERT         | postgres
 public       | sessions                     | REFERENCES     | postgres
 public       | sessions                     | SELECT         | postgres
 public       | sessions                     | TRIGGER        | postgres
 public       | sessions                     | TRUNCATE       | postgres
 public       | sessions                     | UPDATE         | postgres
 public       | sessions                     | DELETE         | service_role
 public       | sessions                     | INSERT         | service_role
 public       | sessions                     | REFERENCES     | service_role
 public       | sessions                     | SELECT         | service_role
 public       | sessions                     | TRIGGER        | service_role
 public       | sessions                     | TRUNCATE       | service_role
 public       | sessions                     | UPDATE         | service_role
 public       | shift_catalogue              | SELECT         | audit_readonly
 public       | shift_catalogue              | DELETE         | copilot_edit
 public       | shift_catalogue              | INSERT         | copilot_edit
 public       | shift_catalogue              | SELECT         | copilot_edit
 public       | shift_catalogue              | UPDATE         | copilot_edit
 public       | shift_catalogue              | DELETE         | postgres
 public       | shift_catalogue              | INSERT         | postgres
 public       | shift_catalogue              | REFERENCES     | postgres
 public       | shift_catalogue              | SELECT         | postgres
 public       | shift_catalogue              | TRIGGER        | postgres
 public       | shift_catalogue              | TRUNCATE       | postgres
 public       | shift_catalogue              | UPDATE         | postgres
 public       | shift_catalogue              | DELETE         | service_role
 public       | shift_catalogue              | INSERT         | service_role
 public       | shift_catalogue              | REFERENCES     | service_role
 public       | shift_catalogue              | SELECT         | service_role
 public       | shift_catalogue              | TRIGGER        | service_role
 public       | shift_catalogue              | TRUNCATE       | service_role
 public       | shift_catalogue              | UPDATE         | service_role
 public       | shift_eligibility            | SELECT         | audit_readonly
 public       | shift_eligibility            | DELETE         | copilot_edit
 public       | shift_eligibility            | INSERT         | copilot_edit
 public       | shift_eligibility            | SELECT         | copilot_edit
 public       | shift_eligibility            | UPDATE         | copilot_edit
 public       | shift_eligibility            | DELETE         | postgres
 public       | shift_eligibility            | INSERT         | postgres
 public       | shift_eligibility            | REFERENCES     | postgres
 public       | shift_eligibility            | SELECT         | postgres
 public       | shift_eligibility            | TRIGGER        | postgres
 public       | shift_eligibility            | TRUNCATE       | postgres
 public       | shift_eligibility            | UPDATE         | postgres
 public       | shift_eligibility            | DELETE         | service_role
 public       | shift_eligibility            | INSERT         | service_role
 public       | shift_eligibility            | REFERENCES     | service_role
 public       | shift_eligibility            | SELECT         | service_role
 public       | shift_eligibility            | TRIGGER        | service_role
 public       | shift_eligibility            | TRUNCATE       | service_role
 public       | shift_eligibility            | UPDATE         | service_role
 public       | shifts                       | SELECT         | audit_readonly
 public       | shifts                       | DELETE         | copilot_edit
 public       | shifts                       | INSERT         | copilot_edit
 public       | shifts                       | SELECT         | copilot_edit
 public       | shifts                       | UPDATE         | copilot_edit
 public       | shifts                       | DELETE         | postgres
 public       | shifts                       | INSERT         | postgres
 public       | shifts                       | REFERENCES     | postgres
 public       | shifts                       | SELECT         | postgres
 public       | shifts                       | TRIGGER        | postgres
 public       | shifts                       | TRUNCATE       | postgres
 public       | shifts                       | UPDATE         | postgres
 public       | shifts                       | DELETE         | service_role
 public       | shifts                       | INSERT         | service_role
 public       | shifts                       | REFERENCES     | service_role
 public       | shifts                       | SELECT         | service_role
 public       | shifts                       | TRIGGER        | service_role
 public       | shifts                       | TRUNCATE       | service_role
 public       | shifts                       | UPDATE         | service_role
 public       | staffing_requirements        | SELECT         | audit_readonly
 public       | staffing_requirements        | DELETE         | copilot_edit
 public       | staffing_requirements        | INSERT         | copilot_edit
 public       | staffing_requirements        | SELECT         | copilot_edit
 public       | staffing_requirements        | UPDATE         | copilot_edit
 public       | staffing_requirements        | DELETE         | postgres
 public       | staffing_requirements        | INSERT         | postgres
 public       | staffing_requirements        | REFERENCES     | postgres
 public       | staffing_requirements        | SELECT         | postgres
 public       | staffing_requirements        | TRIGGER        | postgres
 public       | staffing_requirements        | TRUNCATE       | postgres
 public       | staffing_requirements        | UPDATE         | postgres
 public       | staffing_requirements        | DELETE         | service_role
 public       | staffing_requirements        | INSERT         | service_role
 public       | staffing_requirements        | REFERENCES     | service_role
 public       | staffing_requirements        | SELECT         | service_role
 public       | staffing_requirements        | TRIGGER        | service_role
 public       | staffing_requirements        | TRUNCATE       | service_role
 public       | staffing_requirements        | UPDATE         | service_role
 public       | swap_executions              | SELECT         | audit_readonly
 public       | swap_executions              | DELETE         | copilot_edit
 public       | swap_executions              | INSERT         | copilot_edit
 public       | swap_executions              | SELECT         | copilot_edit
 public       | swap_executions              | UPDATE         | copilot_edit
 public       | swap_executions              | DELETE         | postgres
 public       | swap_executions              | INSERT         | postgres
 public       | swap_executions              | REFERENCES     | postgres
 public       | swap_executions              | SELECT         | postgres
 public       | swap_executions              | TRIGGER        | postgres
 public       | swap_executions              | TRUNCATE       | postgres
 public       | swap_executions              | UPDATE         | postgres
 public       | swap_executions              | DELETE         | service_role
 public       | swap_executions              | INSERT         | service_role
 public       | swap_executions              | REFERENCES     | service_role
 public       | swap_executions              | SELECT         | service_role
 public       | swap_executions              | TRIGGER        | service_role
 public       | swap_executions              | TRUNCATE       | service_role
 public       | swap_executions              | UPDATE         | service_role
 public       | swap_requests                | SELECT         | audit_readonly
 public       | swap_requests                | DELETE         | copilot_edit
 public       | swap_requests                | INSERT         | copilot_edit
 public       | swap_requests                | SELECT         | copilot_edit
 public       | swap_requests                | UPDATE         | copilot_edit
 public       | swap_requests                | DELETE         | postgres
 public       | swap_requests                | INSERT         | postgres
 public       | swap_requests                | REFERENCES     | postgres
 public       | swap_requests                | SELECT         | postgres
 public       | swap_requests                | TRIGGER        | postgres
 public       | swap_requests                | TRUNCATE       | postgres
 public       | swap_requests                | UPDATE         | postgres
 public       | swap_requests                | DELETE         | service_role
 public       | swap_requests                | INSERT         | service_role
 public       | swap_requests                | REFERENCES     | service_role
 public       | swap_requests                | SELECT         | service_role
 public       | swap_requests                | TRIGGER        | service_role
 public       | swap_requests                | TRUNCATE       | service_role
 public       | swap_requests                | UPDATE         | service_role
 public       | user_patterns                | SELECT         | audit_readonly
 public       | user_patterns                | DELETE         | copilot_edit
 public       | user_patterns                | INSERT         | copilot_edit
 public       | user_patterns                | SELECT         | copilot_edit
 public       | user_patterns                | UPDATE         | copilot_edit
 public       | user_patterns                | DELETE         | postgres
 public       | user_patterns                | INSERT         | postgres
 public       | user_patterns                | REFERENCES     | postgres
 public       | user_patterns                | SELECT         | postgres
 public       | user_patterns                | TRIGGER        | postgres
 public       | user_patterns                | TRUNCATE       | postgres
 public       | user_patterns                | UPDATE         | postgres
 public       | user_patterns                | DELETE         | service_role
 public       | user_patterns                | INSERT         | service_role
 public       | user_patterns                | REFERENCES     | service_role
 public       | user_patterns                | SELECT         | service_role
 public       | user_patterns                | TRIGGER        | service_role
 public       | user_patterns                | TRUNCATE       | service_role
 public       | user_patterns                | UPDATE         | service_role
 public       | user_permission_groups       | SELECT         | audit_readonly
 public       | user_permission_groups       | DELETE         | copilot_edit
 public       | user_permission_groups       | INSERT         | copilot_edit
 public       | user_permission_groups       | SELECT         | copilot_edit
 public       | user_permission_groups       | UPDATE         | copilot_edit
 public       | user_permission_groups       | DELETE         | postgres
 public       | user_permission_groups       | INSERT         | postgres
 public       | user_permission_groups       | REFERENCES     | postgres
 public       | user_permission_groups       | SELECT         | postgres
 public       | user_permission_groups       | TRIGGER        | postgres
 public       | user_permission_groups       | TRUNCATE       | postgres
 public       | user_permission_groups       | UPDATE         | postgres
 public       | user_permission_groups       | DELETE         | service_role
 public       | user_permission_groups       | INSERT         | service_role
 public       | user_permission_groups       | REFERENCES     | service_role
 public       | user_permission_groups       | SELECT         | service_role
 public       | user_permission_groups       | TRIGGER        | service_role
 public       | user_permission_groups       | TRUNCATE       | service_role
 public       | user_permission_groups       | UPDATE         | service_role
 public       | users                        | SELECT         | audit_readonly
 public       | users                        | DELETE         | copilot_edit
 public       | users                        | INSERT         | copilot_edit
 public       | users                        | SELECT         | copilot_edit
 public       | users                        | UPDATE         | copilot_edit
 public       | users                        | DELETE         | postgres
 public       | users                        | INSERT         | postgres
 public       | users                        | REFERENCES     | postgres
 public       | users                        | SELECT         | postgres
 public       | users                        | TRIGGER        | postgres
 public       | users                        | TRUNCATE       | postgres
 public       | users                        | UPDATE         | postgres
 public       | users                        | DELETE         | service_role
 public       | users                        | INSERT         | service_role
 public       | users                        | REFERENCES     | service_role
 public       | users                        | SELECT         | service_role
 public       | users                        | TRIGGER        | service_role
 public       | users                        | TRUNCATE       | service_role
 public       | users                        | UPDATE         | service_role
 public       | week_comments                | SELECT         | audit_readonly
 public       | week_comments                | DELETE         | copilot_edit
 public       | week_comments                | INSERT         | copilot_edit
 public       | week_comments                | SELECT         | copilot_edit
 public       | week_comments                | UPDATE         | copilot_edit
 public       | week_comments                | DELETE         | postgres
 public       | week_comments                | INSERT         | postgres
 public       | week_comments                | REFERENCES     | postgres
 public       | week_comments                | SELECT         | postgres
 public       | week_comments                | TRIGGER        | postgres
 public       | week_comments                | TRUNCATE       | postgres
 public       | week_comments                | UPDATE         | postgres
 public       | week_comments                | DELETE         | service_role
 public       | week_comments                | INSERT         | service_role
 public       | week_comments                | REFERENCES     | service_role
 public       | week_comments                | SELECT         | service_role
 public       | week_comments                | TRIGGER        | service_role
 public       | week_comments                | TRUNCATE       | service_role
 public       | week_comments                | UPDATE         | service_role
(798 rows)

