-- ============================================================================
-- INSTRUCTIONS: Update migrate_to_token_only_rpcs.sql with history tracking
-- ============================================================================
--
-- Step 1: At the very beginning (after BEGIN;), add the history table creation:
--
-- CREATE TABLE IF NOT EXISTS public.rota_assignment_history (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   rota_assignment_id bigint NOT NULL,
--   user_id uuid NOT NULL,
--   date date NOT NULL,
--   old_shift_id bigint,
--   old_shift_code text,
--   new_shift_id bigint NOT NULL,
--   new_shift_code text NOT NULL,
--   change_reason text,
--   changed_by uuid,
--   changed_by_name text,
--   changed_at timestamp with time zone DEFAULT now(),
--   FOREIGN KEY (rota_assignment_id) REFERENCES public.rota_assignments(id) ON DELETE CASCADE
-- );
-- 
-- CREATE INDEX IF NOT EXISTS idx_assignment_history_assignment ON public.rota_assignment_history(rota_assignment_id);
-- CREATE INDEX IF NOT EXISTS idx_assignment_history_user_date ON public.rota_assignment_history(user_id, date);
-- CREATE INDEX IF NOT EXISTS idx_assignment_history_changed_at ON public.rota_assignment_history(changed_at DESC);
--
-- ============================================================================
--
-- Step 2: In admin_execute_shift_swap function, add history inserts:
--         (Insert after the rota_assignment_comments section, before RETURN QUERY)
--
--   -- Record history for both assignments
--   INSERT INTO public.rota_assignment_history(
--     rota_assignment_id, user_id, date, old_shift_id, old_shift_code,
--     new_shift_id, new_shift_code, change_reason, changed_by, changed_by_name
--   ) VALUES (
--     v_initiator_shift_id, p_initiator_user_id, p_counterparty_shift_date,
--     v_initiator_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--     v_counterparty_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--     format('Admin swap with %s (was %s on %s)',
--       (SELECT name FROM public.users WHERE id = p_counterparty_user_id),
--       COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--       to_char(p_initiator_shift_date, 'Dy DD Mon')),
--     v_admin_uid,
--     (SELECT name FROM public.users WHERE id = v_admin_uid)
--   );
--
--   INSERT INTO public.rota_assignment_history(
--     rota_assignment_id, user_id, date, old_shift_id, old_shift_code,
--     new_shift_id, new_shift_code, change_reason, changed_by, changed_by_name
--   ) VALUES (
--     v_counterparty_shift_id, p_counterparty_user_id, p_initiator_shift_date,
--     v_counterparty_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--     v_initiator_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--     format('Admin swap with %s (was %s on %s)',
--       (SELECT name FROM public.users WHERE id = p_initiator_user_id),
--       COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--       to_char(p_counterparty_shift_date, 'Dy DD Mon')),
--     v_admin_uid,
--     (SELECT name FROM public.users WHERE id = v_admin_uid)
--   );
--
-- ============================================================================
--
-- Step 3: In admin_approve_swap_request function, add history inserts:
--         (Insert after the rota_assignment_comments section, before RETURN QUERY)
--
--   -- Record history for both assignments
--   INSERT INTO public.rota_assignment_history(
--     rota_assignment_id, user_id, date, old_shift_id, old_shift_code,
--     new_shift_id, new_shift_code, change_reason, changed_by, changed_by_name
--   ) VALUES (
--     v_initiator_shift_id, v_swap_req.initiator_user_id, v_swap_req.counterparty_shift_date,
--     v_initiator_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--     v_counterparty_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--     format('Swap approved with %s (was %s on %s)',
--       (SELECT name FROM public.users WHERE id = v_swap_req.counterparty_user_id),
--       COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--       to_char(v_swap_req.initiator_shift_date, 'Dy DD Mon')),
--     v_admin_uid,
--     (SELECT name FROM public.users WHERE id = v_admin_uid)
--   );
--
--   INSERT INTO public.rota_assignment_history(
--     rota_assignment_id, user_id, date, old_shift_id, old_shift_code,
--     new_shift_id, new_shift_code, change_reason, changed_by, changed_by_name
--   ) VALUES (
--     v_counterparty_shift_id, v_swap_req.counterparty_user_id, v_swap_req.initiator_shift_date,
--     v_counterparty_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--     v_initiator_old_shift_id,
--     COALESCE((SELECT code FROM public.shifts WHERE id = v_initiator_old_shift_id), 'UNKNOWN'),
--     format('Swap approved with %s (was %s on %s)',
--       (SELECT name FROM public.users WHERE id = v_swap_req.initiator_user_id),
--       COALESCE((SELECT code FROM public.shifts WHERE id = v_counterparty_old_shift_id), 'UNKNOWN'),
--       to_char(v_swap_req.counterparty_shift_date, 'Dy DD Mon')),
--     v_admin_uid,
--     (SELECT name FROM public.users WHERE id = v_admin_uid)
--   );
--
-- ============================================================================
--
-- Step 4: Add the new admin_get_assignment_history RPC function to retrieve history
--
-- CREATE OR REPLACE FUNCTION public.admin_get_assignment_history(p_token uuid, p_assignment_id bigint)
-- RETURNS TABLE(
--   id uuid,
--   assignment_id bigint,
--   user_name text,
--   assignment_date date,
--   old_shift_code text,
--   new_shift_code text,
--   reason text,
--   changed_by_name text,
--   changed_at timestamp with time zone
-- )
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- SET search_path TO 'public', 'pg_temp'
-- AS $$
-- DECLARE
--   v_admin_uid uuid;
--   v_is_admin boolean;
-- BEGIN
--   v_admin_uid := public.require_session_permissions(p_token, null);
--   SELECT is_admin INTO v_is_admin FROM public.users WHERE id = v_admin_uid;
--   IF v_is_admin IS NULL OR NOT v_is_admin THEN
--     PERFORM public.require_session_permissions(p_token, ARRAY['rota.view_history']);
--   END IF;
--   RETURN QUERY
--   SELECT
--     ah.id,
--     ah.rota_assignment_id,
--     u.name,
--     ah.date,
--     ah.old_shift_code,
--     ah.new_shift_code,
--     ah.change_reason,
--     ah.changed_by_name,
--     ah.changed_at
--   FROM public.rota_assignment_history ah
--   JOIN public.users u ON u.id = ah.user_id
--   WHERE ah.rota_assignment_id = p_assignment_id
--   ORDER BY ah.changed_at DESC;
-- END;
-- $$;
